"""fix datetime

Revision ID: 76d4525f3af8
Revises: 8c0f6679fae0
Create Date: 2022-11-05 11:01:07.851988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d4525f3af8'
down_revision = '8c0f6679fae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('data_registered', sa.DateTime(), nullable=True))
    op.alter_column('userprofile', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('userprofile', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('userprofile', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('userprofile', 'data_registered')
    # ### end Alembic commands ###
