"""добавление invoice_id

Revision ID: 916201279047
Revises: 76d4525f3af8
Create Date: 2022-11-08 15:11:54.060303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916201279047'
down_revision = '76d4525f3af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderuser', sa.Column('invoice_id', sa.String(length=255), nullable=True))
    op.alter_column('userprofile', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('userprofile', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('userprofile', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('orderuser', 'invoice_id')
    # ### end Alembic commands ###
